# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /es01/software/spack_external/compiler/cmake/3.23.2_gcc12.1.0/bin/cmake

# The command to remove a file.
RM = /es01/software/spack_external/compiler/cmake/3.23.2_gcc12.1.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /es01/home/lvxg/vdb/VectorDB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /es01/home/lvxg/vdb/VectorDB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/es01/software/spack_external/compiler/cmake/3.23.2_gcc12.1.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/es01/software/spack_external/compiler/cmake/3.23.2_gcc12.1.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/es01/software/spack_external/compiler/cmake/3.23.2_gcc12.1.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/es01/software/spack_external/compiler/cmake/3.23.2_gcc12.1.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/es01/software/spack_external/compiler/cmake/3.23.2_gcc12.1.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/es01/software/spack_external/compiler/cmake/3.23.2_gcc12.1.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/es01/software/spack_external/compiler/cmake/3.23.2_gcc12.1.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /es01/home/lvxg/vdb/VectorDB/CMakeFiles /es01/home/lvxg/vdb/VectorDB//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /es01/home/lvxg/vdb/VectorDB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named faiss

# Build rule for target.
faiss: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 faiss
.PHONY : faiss

# fast build rule for target.
faiss/fast:
	$(MAKE) $(MAKESILENT) -f third_party/faiss/faiss/CMakeFiles/faiss.dir/build.make third_party/faiss/faiss/CMakeFiles/faiss.dir/build
.PHONY : faiss/fast

# Manual pre-install relink rule for target.
faiss/preinstall:
	$(MAKE) $(MAKESILENT) -f third_party/faiss/faiss/CMakeFiles/faiss.dir/build.make third_party/faiss/faiss/CMakeFiles/faiss.dir/preinstall
.PHONY : faiss/preinstall

#=============================================================================
# Target rules for targets named faiss_avx2

# Build rule for target.
faiss_avx2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 faiss_avx2
.PHONY : faiss_avx2

# fast build rule for target.
faiss_avx2/fast:
	$(MAKE) $(MAKESILENT) -f third_party/faiss/faiss/CMakeFiles/faiss_avx2.dir/build.make third_party/faiss/faiss/CMakeFiles/faiss_avx2.dir/build
.PHONY : faiss_avx2/fast

#=============================================================================
# Target rules for targets named faiss_avx512

# Build rule for target.
faiss_avx512: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 faiss_avx512
.PHONY : faiss_avx512

# fast build rule for target.
faiss_avx512/fast:
	$(MAKE) $(MAKESILENT) -f third_party/faiss/faiss/CMakeFiles/faiss_avx512.dir/build.make third_party/faiss/faiss/CMakeFiles/faiss_avx512.dir/build
.PHONY : faiss_avx512/fast

#=============================================================================
# Target rules for targets named Tribase

# Build rule for target.
Tribase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tribase
.PHONY : Tribase

# fast build rule for target.
Tribase/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Tribase.dir/build.make src/CMakeFiles/Tribase.dir/build
.PHONY : Tribase/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/main.dir/build.make src/CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named query

# Build rule for target.
query: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 query
.PHONY : query

# fast build rule for target.
query/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/query.dir/build.make src/CMakeFiles/query.dir/build
.PHONY : query/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Tribase"
	@echo "... faiss"
	@echo "... faiss_avx2"
	@echo "... faiss_avx512"
	@echo "... main"
	@echo "... query"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

